@baseUrl = https://my-patientapi-production.up.railway.app

### Registrar usuário
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@email.com",
  "password": "admin"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin"
}
